[package]
name = "file_stoarge_layer"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10" 
aes = "0.8"  
rand = "0.8"  
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
md5 = "0.7"
