

## file storage layer
DEFAULT_SHARD_SIZE: 1024  # Shard size in bytes
DEFAULT_ERROR_CORRECTION: 10 # Error correction level


## network layer
BUFFER_SIZE: 2048  # Buffer size for reading and writing data in network (bytes)