# commands.py

NODE_CON_ADDR = "NODE_CON_ADDR"
CMD_JOIN_MSG = "CMD_JOIN_MSG"
ASK_RANDOM_NODE = "ASK_RANDOM_NODE"
ASK_NODES_TO_CONNECT = "ASK_NODES_TO_CONNECT"
MULTI_CONN_ADDR = "MULTI_CONN_ADDR"
DISCONNECT_MSG = "!DISCONNECT"
